@{
    pd = 'PenDown'
    pu = 'PenUp'
    fd = 'Forward'
    down = 'PenDown'
    up = 'PenUp'
    l = 'Left'
    r = 'Right'
    xPos = 'xcor'
    yPos = 'ycor'
    SetPos = 'GoTo'
    SetPosition = 'GoTo'
    Back = 'Backward'
    bk = 'Backward'
}